name: Test UAT Workflow

on:
  # For details on creating a repository_dispatch event see: https://docs.github.com/en/rest/repos/repos#create-a-repository-dispatch-event
  repository_dispatch:
    types:
      - webhook-for-uat

jobs:
  test_runner_workflow_job:
    name: Run UAT Tests
    uses: ./.github/workflows/test-runner.yml
    with:
      TARGET_NAME: uat
      TARGET_DOMAIN: ${{ vars.UAT_DOMAIN }}
      TARGET_SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL_UAT }}
    secrets: inherit